WandB Integration
Bhuvanesh-Verma/word_embedding pull request #12
Opened 2021-08-01 15:50 UTC by Bhuvanesh-Verma

1. Word Analogy task function added to utils.
2. [WandB](https://wandb.ai/) framework for project visualization is added.
3. questions-words.txt dataset added. It will be used for word analogy evaluation task.

2021-08-02 09:41 UTC, TamaraAtanasoska requested changes
Thanks for this great work! The word_analogy maybe we can merge to master once it is ready to work with data, otherwise 👍 or LGTM as people would say 🥳

2021-08-02 09:41 UTC, TamaraAtanasoska commented on requirements.txt
> +wandb==0.11
thanks for adding the requirements.txt!

2021-08-02 09:41 UTC, TamaraAtanasoska commented on utils.py
> +        similarity = cosine_similarity(diff1, diff2)
I like the sklearn implementation too, I will use it as well 👍

2021-08-03 06:50 UTC, Bhuvanesh-Verma commented
I think we should merge this as this is related to wandb integration. I will create another branch concerning word_analogy task.

2021-08-03 08:17 UTC, merged